/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as RegisterImport } from "./routes/register";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthenticatedImport } from "./routes/authenticated";
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index";

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/authenticated",
  path: "/authenticated",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: "/_authenticated/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/authenticated": {
      id: "/authenticated";
      path: "/authenticated";
      fullPath: "/authenticated";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/authenticated": typeof AuthenticatedRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/": typeof AuthenticatedIndexRoute;
}

export interface FileRoutesByTo {
  "/authenticated": typeof AuthenticatedRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/": typeof AuthenticatedIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/authenticated": typeof AuthenticatedRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/authenticated" | "/login" | "/register" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/authenticated" | "/login" | "/register" | "/";
  id:
    | "__root__"
    | "/authenticated"
    | "/login"
    | "/register"
    | "/_authenticated/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/authenticated",
        "/login",
        "/register",
        "/_authenticated/"
      ]
    },
    "/authenticated": {
      "filePath": "authenticated.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
